// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJh3hq1d1g9QIb6Or3Uq6fziNOfPAEhJg',
    appId: '1:720882643917:web:f2444e737dc38d505b8a84',
    messagingSenderId: '720882643917',
    projectId: 'fir-auth-f73c3',
    authDomain: 'fir-auth-f73c3.firebaseapp.com',
    storageBucket: 'fir-auth-f73c3.appspot.com',
    measurementId: 'G-YK5412Z21C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wK8yoBPQri7gnEmFWd_-qHPQSueGYq4',
    appId: '1:720882643917:android:1c92b319a52ba0075b8a84',
    messagingSenderId: '720882643917',
    projectId: 'fir-auth-f73c3',
    storageBucket: 'fir-auth-f73c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSjI-mIonapombTfFrdWQbmOoVSU6l6I',
    appId: '1:720882643917:ios:d357c2a9037ad48e5b8a84',
    messagingSenderId: '720882643917',
    projectId: 'fir-auth-f73c3',
    storageBucket: 'fir-auth-f73c3.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaSjI-mIonapombTfFrdWQbmOoVSU6l6I',
    appId: '1:720882643917:ios:9ae3b40df4784d6e5b8a84',
    messagingSenderId: '720882643917',
    projectId: 'fir-auth-f73c3',
    storageBucket: 'fir-auth-f73c3.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
